server:
  port : 8081
  
spring:
  kafka:
    client-id: player1
    consumer:
      group-id: player1
  
gof:
  kafka:
    ingress-topic: player1-ingress    
    peer-ingress-topic: player2-ingress    
  