server:
  port : 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    client-id: control-panel
    consumer:
      auto-offset-reset: earliest
      group-id: control-panel

gof:
  max-number : 99
  kafka:
    player1-ingress-topic: player1-ingress
    player2-ingress-topic: player2-ingress
  