server:
  port : 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    client-id: control-panel
    consumer:
      auto-offset-reset: earliest
      group-id: control-panel

gof:
  service-name: control-panel
  player1-service-name: player1
  player2-service-name: player2
  max-number: 99
  kafka:
    events-topic: gof-events
  